### ISSUE TITLE
Markers do not adapt to the size of the window / screen

### ISSUE THREAD

**Issue by todio** [AskiaADX/Slider#1]
![capture](https://cloud.githubusercontent.com/assets/11976921/7417250/c7592c76-ef5c-11e4-89c4-5f97cc9d3f40.PNG)
(supposed to rate from one to  ten)
![capture2](https://cloud.githubusercontent.com/assets/11976921/7417282/f853284a-ef5c-11e4-99d0-e6a37d30b548.PNG)

**Comment by Djedj** [comment]
should be fixed in v1.1.13
