### ISSUE TITLE
markers not always generated

### ISSUE THREAD

**Issue by FlagBenett** [AskiaADX/Slider#7]
In the case where a Slider ranges from 0 (minimal value) to 11 (maximal value), the last marker with value = 11 is not created. The problem doesn't happen on 0 to 12 range (or above)

[slider_0_to_11.zip](https://github.com/AskiaADX/Slider/files/3276638/slider_0_to_11.zip)

**Comment by prabathgamage** [comment]
Hi stephen,
This is fixed on v3.0.2.

Thanks.
