### ISSUE TITLE
sliders pips in a 2-level loop

### ISSUE THREAD

**Issue by FlagBenett** [AskiaADX/Slider#8]
When the slider is in a 2-level loop, the pips show the Question.ParentLoop value rather than the Question.Value.

![Sans titre](https://user-images.githubusercontent.com/11921176/59276390-776da680-8c5e-11e9-9bd1-33d4ea6ef222.png)

[looped_sliders.zip](https://github.com/AskiaADX/Slider/files/3276696/looped_sliders.zip)

**Comment by prabathgamage** [comment]
Hi stephen,

This is fixed on v3.0.3.
thanks.
